name: flutter_mcp_datasources
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.5

dependencies:
  shared_preferences:
  flutter_mcp_entities:

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
