name: flutter_mcp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  window_manager:
  flutter_svg:

  # BLoC & State Management
  flutter_bloc:
  bloc:
  equatable:

  # Dependency Injection
  get_it:

  # Data & Network
  shared_preferences:
  mcp_dart:
  http:

  # Utilities
  uuid:
  collection:
  flutter_markdown:
  dartz:
  talker_bloc_logger:

  flutter_mcp_datasources:
  flutter_mcp_entities:
  flutter_mcp_repositories:
  flutter_mcp_usecases:
  flutter_mcp_widgets:
  flutter_mcp_state:

  llm_kit:

dev_dependencies:
  melos:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/fonts/Copernicus/
    - assets/fonts/StyreneB/
    - assets/icons/
    - assets/images/

  fonts:
    - family: StyreneB
      fonts:
        - asset: assets/fonts/StyreneB/StyreneB-Thin-Trial-BF63f6cc84a4246.otf
          weight: 100
        - asset: assets/fonts/StyreneB/StyreneB-ThinItalic-Trial-BF63f6cbe8d3333.otf
          weight: 100
          style: italic
        - asset: assets/fonts/StyreneB/StyreneB-Light-Trial-BF63f6cbe64b47b.otf
          weight: 300
        - asset: assets/fonts/StyreneB/StyreneB-LightItalic-Trial-BF63f6cbe9d67d1.otf
          weight: 300
          style: italic
        - asset: assets/fonts/StyreneB/StyreneB-Regular-Trial-BF63f6cbe9db1d5.otf
          weight: 400
        - asset: assets/fonts/StyreneB/StyreneB-RegularItalic-Trial-BF63f6cbe5c1942.otf
          weight: 400
          style: italic
        - asset: assets/fonts/StyreneB/StyreneB-Medium-Trial-BF63f6cc85760c2.otf
          weight: 500
        - asset: assets/fonts/StyreneB/StyreneB-MediumItalic-Trial-BF63f6cc84a421a.otf
          weight: 500
          style: italic
        - asset: assets/fonts/StyreneB/StyreneB-Bold-Trial-BF63f6cbe9f13bb.otf
          weight: 700
        - asset: assets/fonts/StyreneB/StyreneB-BoldItalic-Trial-BF63f6cbe6863e6.otf
          weight: 700
          style: italic
        - asset: assets/fonts/StyreneB/StyreneB-Black-Trial-BF63f6cbe3dc69b.otf
          weight: 900
        - asset: assets/fonts/StyreneB/StyreneB-BlackItalic-Trial-BF63f6cbe2d985b.otf
          weight: 900
          style: italic

    - family: Copernicus
      fonts:
        - asset: assets/fonts/Copernicus/CopernicusTrial-Book.ttf
        - asset: assets/fonts/Copernicus/CopernicusTrial-BookItalic.ttf
          style: italic
        - asset: assets/fonts/Copernicus/CopernicusTrial-Medium.ttf
          weight: 500
        - asset: assets/fonts/Copernicus/CopernicusTrial-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Copernicus/CopernicusTrial-Semibold.ttf
          weight: 600
        - asset: assets/fonts/Copernicus/CopernicusTrial-SemiboldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Copernicus/CopernicusTrial-Bold.ttf
          weight: 700
        - asset: assets/fonts/Copernicus/CopernicusTrial-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Copernicus/CopernicusTrial-Extrabold.ttf
          weight: 800
        - asset: assets/fonts/Copernicus/CopernicusTrial-ExtraboldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Copernicus/CopernicusTrial-Heavy.ttf
          weight: 900
        - asset: assets/fonts/Copernicus/CopernicusTrial-HeavyItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Copernicus/CopernicusTrial-Bold-BF6616045097aac.ttf
          weight: 700

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
